### ISSUE TITLE
VSIX will not install on VS 2015

### ISSUE THREAD

**Issue by BrainCrumbz** [BrainCrumbz/NSpec.VsAdapter#2]
See [comment](https://github.com/mattflo/NSpec/issues/108#issuecomment-182266594) on NSpec issue, copied here for simplicity:

~~~
10.02.2016 10:08:14 - Microsoft VSIX Installer
10.02.2016 10:08:14 - -------------------------------------------
10.02.2016 10:08:14 - Initializing Install...
10.02.2016 10:08:14 - Extension Details...
10.02.2016 10:08:14 - 	Identifier         : BrainCrumbz.NSpec.VsAdapter
10.02.2016 10:08:14 - 	Name               : NSpec VS Adapter
10.02.2016 10:08:14 - 	Author             : BrainCrumbz
10.02.2016 10:08:14 - 	Version            : 0.1
10.02.2016 10:08:14 - 	Description        : A test adapter to run NSpec tests from Test Explorer window in Visual Studio 2013 and later.
10.02.2016 10:08:14 - 	Locale             : en-US
10.02.2016 10:08:14 - 	MoreInfoURL        : https://github.com/BrainCrumbz/NSpec.VsAdapter
10.02.2016 10:08:14 - 	InstalledByMSI     : False
10.02.2016 10:08:14 - 	SupportedFrameworkVersionRange : [4.5,)
10.02.2016 10:08:14 - 
10.02.2016 10:08:14 - 	SignatureState     : Unsigned
10.02.2016 10:08:14 - 	Supported Products : 
10.02.2016 10:08:14 - 		Microsoft.VisualStudio.Pro
10.02.2016 10:08:14 - 			Version : [12.0]
10.02.2016 10:08:14 - 
10.02.2016 10:08:14 - 	References         : 
10.02.2016 10:08:14 - Signature Details...
10.02.2016 10:08:14 - 	Extension is not signed.
10.02.2016 10:08:14 - 
10.02.2016 10:08:14 - Searching for applicable products...
10.02.2016 10:08:14 - Found installed product - Microsoft Visual Studio Enterprise 2015
10.02.2016 10:08:14 - Found installed product - Microsoft Visual Studio Professional 2015
10.02.2016 10:08:14 - Found installed product - Microsoft Visual Studio Community 2015
10.02.2016 10:08:14 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
10.02.2016 10:08:14 - Found installed product - Global Location
10.02.2016 10:08:14 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   bei VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   bei VSIXInstaller.App.InitializeInstall()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
~~~

**Comment by BrainCrumbz** [comment]
That was an issue with extension manifest, now addressed in [this commit](https://github.com/BrainCrumbz/NSpec.VsAdapter/commit/3abe6abdf6a630f6f5f484d002541b752842b0d5) and release as [v0.1.1](https://github.com/BrainCrumbz/NSpec.VsAdapter/releases/tag/v0.1.1).

@sickboy We tried it on VS2015 (Community Ed.): good news is that install goes fine (it detects both VS2013 and VS2015). Bad news is that we opened a sample solution in VS2015 and:
1. test discovery seems to be only triggered upon solution opening, not after builds.
1. after test discovery runs (successfully), no test in listed in Test Explorer window.

**Comment by sickboy** [comment]
@BrainCrumbz thanks, I can confirm the install on VS2015 Enterprise.

**Comment by BrainCrumbz** [comment]
:+1: thanks for quick feedback. As you can see from new Github issues, adapter seems to suffer with VS2015 yet.

**Comment by franklinyu** [comment]
Same issue from Visual Studio 2017 Community?

**Comment by BrainCrumbz** [comment]
Hi @franklinyu . Yes ... and no. We don't have (yet) a Test Adapter working with VS 2017, its test framework has somehow changed since VS2015 and we did not catch up with changes (mainly because we ourselves are still cautious on switching to VS2017).

If you feel like giving a hand with the job, just shout!

**Comment by franklinyu** [comment]
I thought this extension is also targeting VS 2017, because the README says

> It runs tests in VS 2013, 2015 and 2017 from projects targeting classic .NET Framework.

So maybe we can have a new issue to track support for VS 2017?

**Comment by BrainCrumbz** [comment]
Oh well ... now I have mixed thoughts. For one thing, this adapter is not ready for .NET Core projects, while instead it is working for classic .NET Framework projects.

Now, I'd say, yes please! Could you open a new issue related to VS 2017 describing the problem you faced? Was that at install time, or at test-detection time, or.... 

Thanks!
